-- MySQL Script generated by MySQL Workbench
-- Tue Nov 12 16:31:30 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema db_projeto_modelo
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `db_projeto_modelo` ;

-- -----------------------------------------------------
-- Schema db_projeto_modelo
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_projeto_modelo` DEFAULT CHARACTER SET utf8 ;
USE `db_projeto_modelo` ;

-- -----------------------------------------------------
-- Table `db_projeto_modelo`.`aluno_aln`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_projeto_modelo`.`aluno_aln` ;

CREATE TABLE IF NOT EXISTS `db_projeto_modelo`.`aluno_aln` (
  `id_aln` INT(11) NOT NULL AUTO_INCREMENT,
  `nome_aln` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`id_aln`))
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `db_projeto_modelo`.`conta_con`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_projeto_modelo`.`conta_con` ;

CREATE TABLE IF NOT EXISTS `db_projeto_modelo`.`conta_con` (
  `id_conta` INT(11) NOT NULL AUTO_INCREMENT,
  `ds_usuario_con` VARCHAR(45) NOT NULL,
  `ds_email_con` VARCHAR(120) NOT NULL,
  `ds_foto_con` VARCHAR(20) NOT NULL,
  `ds_senha_con` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`id_conta`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `db_projeto_modelo`.`mestre_mst`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_projeto_modelo`.`mestre_mst` ;

CREATE TABLE IF NOT EXISTS `db_projeto_modelo`.`mestre_mst` (
  `id_mst` INT(11) NOT NULL AUTO_INCREMENT,
  `ds_nome_mst` VARCHAR(100) NOT NULL,
  `ds_sexo_mst` VARCHAR(1) NOT NULL,
  `ds_estadocivil_mst` VARCHAR(1) NOT NULL,
  `dt_nascimento_mst` DATETIME NOT NULL,
  `lg_situacao_mst` TINYINT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`id_mst`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `db_projeto_modelo`.`detalhe_dtl`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_projeto_modelo`.`detalhe_dtl` ;

CREATE TABLE IF NOT EXISTS `db_projeto_modelo`.`detalhe_dtl` (
  `id_dtl` INT(11) NOT NULL AUTO_INCREMENT,
  `ds_nome_dtl` VARCHAR(60) NOT NULL,
  `ds_endereco_dtl` VARCHAR(200) NOT NULL,
  `ds_bairro_dtl` VARCHAR(30) NOT NULL,
  `ds_cidade_dtl` VARCHAR(30) NOT NULL,
  `ds_telefone_dtl` VARCHAR(15) NOT NULL,
  `mestre_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id_dtl`),
  INDEX `mestre_id` (`mestre_id` ASC),
  CONSTRAINT `detalhe_dtl_ibfk_1`
    FOREIGN KEY (`mestre_id`)
    REFERENCES `db_projeto_modelo`.`mestre_mst` (`id_mst`))
ENGINE = InnoDB
AUTO_INCREMENT = 14
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `db_projeto_modelo`.`pessoa_pes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_projeto_modelo`.`pessoa_pes` ;

CREATE TABLE IF NOT EXISTS `db_projeto_modelo`.`pessoa_pes` (
  `id_pes` INT(11) NOT NULL AUTO_INCREMENT,
  `nome_pes` VARCHAR(80) NULL DEFAULT NULL,
  `dt_nascimento_pes` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id_pes`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `db_projeto_modelo`.`empregado_emp`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_projeto_modelo`.`empregado_emp` ;

CREATE TABLE IF NOT EXISTS `db_projeto_modelo`.`empregado_emp` (
  `id_emp` INT(11) NOT NULL AUTO_INCREMENT,
  `matricula_emp` VARCHAR(20) NULL DEFAULT NULL,
  `nm_guerra_emp` VARCHAR(20) NULL DEFAULT NULL,
  `dt_admissao_emp` DATETIME NULL DEFAULT NULL,
  `pessoa_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id_emp`),
  UNIQUE INDEX `pessoa_id` (`pessoa_id` ASC),
  CONSTRAINT `empregado_emp_ibfk_1`
    FOREIGN KEY (`pessoa_id`)
    REFERENCES `db_projeto_modelo`.`pessoa_pes` (`id_pes`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `db_projeto_modelo`.`modelo_mod`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_projeto_modelo`.`modelo_mod` ;

CREATE TABLE IF NOT EXISTS `db_projeto_modelo`.`modelo_mod` (
  `id_modelo` INT(11) NOT NULL AUTO_INCREMENT,
  `ds_sigla_mod` VARCHAR(45) NOT NULL,
  `ds_nome_mod` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id_modelo`))
ENGINE = InnoDB
AUTO_INCREMENT = 65
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `db_projeto_modelo`.`professor_prf`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_projeto_modelo`.`professor_prf` ;

CREATE TABLE IF NOT EXISTS `db_projeto_modelo`.`professor_prf` (
  `id_prf` INT(11) NOT NULL AUTO_INCREMENT,
  `nome_prf` VARCHAR(50) NULL DEFAULT NULL,
  `dt_criacao_prf` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id_prf`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `db_projeto_modelo`.`professor_aluno_pfa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_projeto_modelo`.`professor_aluno_pfa` ;

CREATE TABLE IF NOT EXISTS `db_projeto_modelo`.`professor_aluno_pfa` (
  `id_prf` INT(11) NOT NULL,
  `id_aln` INT(11) NOT NULL,
  PRIMARY KEY (`id_prf`, `id_aln`),
  INDEX `id_aln` (`id_aln` ASC),
  CONSTRAINT `professor_aluno_pfa_ibfk_1`
    FOREIGN KEY (`id_prf`)
    REFERENCES `db_projeto_modelo`.`professor_prf` (`id_prf`),
  CONSTRAINT `professor_aluno_pfa_ibfk_2`
    FOREIGN KEY (`id_aln`)
    REFERENCES `db_projeto_modelo`.`aluno_aln` (`id_aln`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `db_projeto_modelo`.`tb_empresa_emp`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_projeto_modelo`.`tb_empresa_emp` ;

CREATE TABLE IF NOT EXISTS `db_projeto_modelo`.`tb_empresa_emp` (
  `id_empresa` INT(11) NOT NULL AUTO_INCREMENT,
  `ds_nomefantasia_emp` VARCHAR(60) NOT NULL,
  `ds_razaosocial_emp` VARCHAR(100) NOT NULL,
  `ds_cnpj_emp` VARCHAR(25) NOT NULL,
  `ds_cidade_emp` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id_empresa`))
ENGINE = InnoDB
AUTO_INCREMENT = 67
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
